/*
* Copyright (C) 2019 Boyuan Yang <by.yang@pitt.edu>
*
* All Rights Reserved.
*/

#ifndef ANDROID_SENSORS_H
#define ANDROID_SENSORS_H


#include <hardware/hardware.h>
#include <hardware/sensors.h>

__BEGIN_DECLS

#define PURESTUB_SENSORS_ACCELERATION_HANDLE (133)
#define PURESTUB_SENSORS_GYROSCOPE_HANDLE    (134)
#define PURESTUB_SENSORS_GAMEROTATIONVECTOR_HANDLE    (135)
#define PURESTUB_SENSORS_ROTATIONVECTOR_HANDLE    (136)

#define PURESTUB_SENSORS_IDENTIFIER_ACCELEROMETER (13)
#define PURESTUB_SENSORS_IDENTIFIER_GYROSCOPE     (14)
#define PURESTUB_SENSORS_IDENTIFIER_GAMEROTATIONVECTOR    (15)
#define PURESTUB_SENSORS_IDENTIFIER_ROTATIONVECTOR    (16)


__END_DECLS

#endif  /* ANDROID_SENSORS_H */
